#ifndef PORTS_H
#define PORTS_H

#define LEFT_FRONT_MOTOR 20
#define LEFT_BACK_MOTOR 19
#define RIGHT_FRONT_MOTOR 18
#define RIGHT_BACK_MOTOR 17

#define ROLLER_MOTOR 10
#define SUCC_MOTOR 9

#define SHOOTER_R_MOTOR 15
#define SHOOTER_C_MOTOR 14

#define SHOOT_PORT 'H'
#define ODOMETRY_PORT_0 'C'
#define ODOMETRY_PORT_1 'D'

#endif