#ifndef PORTS_H
#define PORTS_H

#define LEFT_FRONT_MOTOR 12
#define LEFT_BACK_MOTOR 11
#define RIGHT_FRONT_MOTOR 13
#define RIGHT_BACK_MOTOR 14

#define ROLLER_MOTOR 16
#define SUCC_MOTOR 17

#define SHOOTER_R_MOTOR 20
#define SHOOTER_C_MOTOR 19

#define SHOOT_PORT 'A'
#define ODOMETRY_PORT_0 'C'
#define ODOMETRY_PORT_1 'D'

#endif